apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ml-project
  name: backend-deployment
  labels:
    name: backend-deployment
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: abdoussalam/backend-ml-project:v3
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql-service 
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: ml-project-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ml-project-secret
              key: MYSQL_PASSWORD
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: FLASK_ENV