apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ml-project
  name: frontend-deployment
  labels:
    name: frontend-deployment
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: abdoussalam/frontend-ml-project:v1
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontent-configmap
              key: REACT_APP_BACKEND_URL
        - name: CHOKIDAR_USEPOLLING
          valueFrom:
            configMapKeyRef:
              name: frontent-configmap
              key: CHOKIDAR_USEPOLLING