apiVersion: v1
kind: Service
metadata:
  namespace: ml-project
  name: frontend-service
  labels:
    name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
      name: frontend-cluster-ip
